# Generated by Django 2.2 on 2018-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinformation',
            fields=[
                ('id', models.AutoField(db_column='UID', max_length=11, primary_key=True, serialize=False)),
                ('userName', models.CharField(db_column='userName', max_length=50)),
                ('passWord', models.CharField(db_column='passWord', max_length=25)),
                ('mobile', models.CharField(db_column='mobile', max_length=11)),
                ('sex', models.CharField(db_column='sex', max_length=10)),
            ],
        ),
    ]
