# Generated by Django 2.2 on 2018-06-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='createTime',
            field=models.DateField(blank=True, db_column='createTime', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='updateTime',
            field=models.DateField(blank=True, db_column='updateTime', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='mobile',
            field=models.CharField(blank=True, db_column='mobile', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(blank=True, db_column='sex', max_length=10),
        ),
    ]
