# Generated by Django 2.2 on 2018-06-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20180628_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='createTime',
            field=models.DateField(blank=True, db_column='createTime', default='2018.01.01', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='updateTime',
            field=models.DateField(blank=True, db_column='updateTime', default='2018.01.01', max_length=20),
        ),
    ]
