# Generated by Django 2.2 on 2018-06-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20180628_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='createTime',
            field=models.DateField(auto_now_add=True, db_column='createTime', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='updateTime',
            field=models.DateField(auto_now=True, db_column='updateTime', max_length=20),
        ),
    ]
