# Generated by Django 2.2 on 2018-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20180628_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='createTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
